FROM node:20-alpine AS builder

WORKDIR /app/apps/web
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

COPY apps/web/package.json apps/web/package-lock.json ./
RUN npm ci

COPY apps/web ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app/apps/web

RUN apk add --no-cache tzdata

ENV NODE_ENV=production
ENV TZ=Asia/Seoul
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

COPY --from=builder /app/apps/web/.next ./.next
COPY --from=builder /app/apps/web/package.json ./package.json
COPY --from=builder /app/apps/web/node_modules ./node_modules
COPY --from=builder /app/apps/web/next.config.mjs ./next.config.mjs

EXPOSE 3000

CMD ["npm", "run", "start"]
